name: php-ago

services:
    app:
        build:
            context: .
        image: php-ago
        container_name: php-ago
        volumes:
            - .:/app:z
        environment:
            - TERM=xterm-256color
        tty: true
        stdin_open: true
